apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  jupyterhub-mapping
  namespace: customer-ns
spec:
  hostname: "*"
  prefix: /jupyter/
  service: proxy-public
  rewrite: /jupyter/
  allow_upgrade:
    - websocket