---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  prefect-mapping
  namespace: customer-ns
spec:
  hostname: "*"
  prefix: /prefect
  service: prefect-server-ui:8080
  rewrite: /
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: prefect-apollo-mapping
  namespace: customer-ns
spec:
  prefix: /graphql
  rewrite: /
  service: prefect-server-apollo:4200
  hostname: "*"
---